[tool.poetry]
name = "notifications-android-tv"
version = "1.2.1"
description = "Python API for sending notifications to Android/Fire TVs"
authors = ["Rami Mosleh <engrbm87@gmail.com>"]
homepage = "https://github.com/engrbm87/notifications_android_tv"
repository = "https://github.com/engrbm87/notifications_android_tv/releases"
readme = "README.md"
license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.27.0"

[tool.poetry.group.dev.dependencies]
colorlog = "^6.6.0"
ruff = "^0.3.7"
pre-commit = "^3.7.1"
pytest = "^7.1.2"
pytest-httpx = ">0.15,<1"
pytest-asyncio = "^0.16.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
