[tool.poetry]
name = "codeblueprints"
version = "0.1.0-alpha.1"
description = "Automates code planning by mapping issues(softwares requirements) to actionable modifications in your codebase, preparing for future code generation."
authors = [
  "Liu Yong <13311102957@163.com>"
]
maintainers = [
  "Liu Yong <13311102957@163.com>"
]
license = "Apache-2.0"
readme = "README.rst"
homepage = "https://github.com/esperyong/codeblueprints"
repository = "https://github.com/esperyong/codeblueprints"
documentation = "https://github.com/esperyong/codeblueprints/blob/master/changelog.md"

[tool.poetry.dependencies]
python = "^3.8"
diskcache = "*"
networkx = "<3.3"
grep_ast = "*"
tqdm = "4.66.4"
pygments = "*"
tree-sitter = "0.21.3"
tree-sitter-languages = "1.10.2"
typing-extensions = "4.12.2"

[tool.poetry.dev-dependencies]
pytest = ">=7.4.3,<8.0.0"
pytest-cov = ">=4.1.0,<5.0.0"
pytest-ordering = ">=0.6,<1.0"
pytest-mock = ">=3.12.0,<4.0.0"
invoke = ">=2.2.0,<3.0.0"
xlrd = ">=2.0.1,<3.0.0"
Faker = ">=20.1.0,<21.0.0"
factory_boy = ">=3.3.0,<4.0.0"
freezegun = ">=1.2.2,<2.0.0"
model-bakery = ">=1.17.0,<2.0.0"

[tool.poetry.scripts]

[tool.poetry.plugins]

[tool.mypy]
files = "."
strict = true
warn_unreachable = true
warn_no_return = true

[[tool.mypy.overrides]]
module = "tests.*"
allow_untyped_defs = true
disable_error_code = "attr-defined"
