[tool.poetry]
name = "pypsicquic"
version = "0.1.0"
description = ""
authors = ["glaunay <pitooon@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9, <4.0"
requests = "^2.28.1"
networkx = "^2.8.7"
scipy = "^1.9.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
