[build-system]
requires = ["flit_core >= 3.4"]
build-backend = "flit_core.buildapi"

[project]
name = "django-fixtures-extractor"
version = "0.1.2"
description = "Set of tools to extract fixtures from Django models navigating through the relationships of a given model to get a usable subset of the database."
readme = "README.rst"
readme-content-type = "text/x-rst"
license = { file = "LICENSE" }
authors = [{ name = "Mati Barriento", email = "elmatibarriento@gmail.com" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["Django>=1.11"]

[project.urls]
"Homepage" = "https://github.com/matibarriento/django-fixture-extractor"

[tool.flit.module]
name = "fixtures_extractor"
