[tool.poetry]
name = "swifr"
version = "2.2.0"
description = "SWIF(r) - SWeep Inference Framework(controlling for correlation) - package for detecting adaptation in population data"
authors = ["Lauren Alpert Sugden <lauren.v.sugden@gmail.com>", "Kaileigh Ahlquist", "Joseph Paik", "Sohini Ramachandran"]
license = "GPL-3.0"
readme = "README.md"
homepage = "https://github.com/ramachandran-lab/SWIFr"
keywords = ["genomics", "population genetics", "adaptation"]
packages = [{ include = "swifr_pkg" }]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
numpy = "1.26.4"
pyparsing = "2.4.2"
matplotlib = "^3.9.0"
cycler = "^0.12.1"
python-dateutil = "^2.9.0.post0"
six = "^1.16.0"
future = "^1.0.0"

[tool.poetry.scripts]
swifr_train = "swifr_pkg.SWIFr_train:main"
swifr_test = "swifr_pkg.SWIFr:main"
calibration = "swifr_pkg.calibration:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"




