[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ops-py-cert-report"
description = "Output a Cert expire report"
license = {file = "LICENSE"}
version = "4.2.1"
dynamic = ["readme", "dependencies"]

[tool.setuptools.dynamic]
readme = {file = "README.md", content-type = "text/markdown"}
dependencies = {file = [""]}
