[tool.poetry]
name = "nillion-python-helpers"
version = "0.2.0"
description = ""
authors = ["Jos√© Cabrero-Holgueras <jose.cabrero@nillion.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
#py-nillion-client = "^0.2.1"
python-dotenv = "1.0.0"
pytest-asyncio = "^0.23.7"
cosmpy = "^0.9.2"

# [tool.poetry.scripts]
# bootstrap-local-environment = "nillion_python_helpers.scripts.bootstrap_local_environment:main"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
