[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "astmain"
version = "0.0.141"
description = "æè¿°:æˆ‘çš„å·¥å…·åŒ…ðŸ’—2024/06/28ðŸ’—10_19_23#ðŸ’— pip install  astmain==0.0.141  "
dependencies = ["tornado", "requests", "pyppeteer", "pyppeteer_stealth", "arrow"]
readme = "README.md"

[[project.authors]]
name = "xupeng"
email = "1311192345@qq.com"
