[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "conector-mysql-sgd"
version = "0.0.4"
dependencies = [
    "sqlalchemy",
    "mysql-connector-python",
    "pandas",
]

# OR
[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["src"]  # ["."] by default
#include = ["*.py"]  # ["*"] by default
namespaces = false  # true by default
