[package]
name = "pymainprocess"
version = "0.1.3"
description = "Python Process Module"
license = "MIT"
authors = ["Kevin Alexander Krefting <kevin@krefting.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pymainprocess"
crate-type = ["cdylib"]

[dependencies]
dotenv = "0.15.0"
fs_extra = "1.3.0"
libc = "0.2.155"
nix = { version = "0.29.0", features = ["process"] }
pyo3 = "0.21.1"
pytype = "0.1.0"
sys-info = "0.9.1"
tempfile = "3.10.1"
which = "6.0.1"
