[build-system]
requires = [
    "maturin>=1.6,<2.0",
    "patchelf"
]
build-backend = "maturin"

[project]
name = "pymainprocess"
version = "0.1.3"
description = "Python Process Module, written in Python and Rust"
license = "MIT"
authors = [
    { name = "Kevin Alexander Krefting", email = "kakrefting@gmail.com" }
]
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
homepage = "https://github.com/pymainprocess/pymainprocess"

[tool.maturin]
features = ["pyo3/extension-module"]
